# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cd91cf530c61db75f7816901fc69c3713361c17de8644192235615205d75e99e12d11af8351df2926a556ce354e36319884f4a39a0db6947290bf5b56c70500

test:
  secret_key_base: 082bc1fac92531f350bca1bf238199c02d3d1901c042aecf221b9610cd958a0892567b9a8b9c604c2b0ec5bae6051b16ac5446a7b476ab3cda5771a8b2b12552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
